export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  safelist: [
    'inline-flex',
    'items-center',
    'justify-center',
    'rounded-md',
    'text-sm',
    'font-medium',
    'transition-colors',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-primary',
    'focus-visible:ring-offset-2',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
    'ring-offset-background',
    'bg-primary',
    'hover:bg-primary/90',
    'text-white',
    'border',
    'border-primary',
    'text-primary',
    'hover:bg-primary/10',
    'h-10',
    'px-4',
    'py-2',
    'h-9',
    'px-3',
    'h-11',
    'px-8',
    'w-10',
    'p-0',
    'flex',
    'w-full',
    'border-gray-300',
    'bg-white',
    'placeholder-gray-500',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      colors: {
        primary: '#6366f1',
      },
    },
  },
  plugins: [],
}
